### ISSUE TITLE
Filename flag not working

### ISSUE THREAD

**Issue by JessikaBryant** [EvanForsythe/Squeakuences#35]
When adding -f <Name> the system came up with an error shown below

./squeakuences.py -i /scratch/bryantj2/bb485/week09/DirtyGenomes/ -o /scratch/bryantj2/bb485/week09/CleanGenomes -l -f Sbicolor.fa
usage: squeakuences.py [-h] -i file_or_dir_path -o dir_path [-l] [-f]
squeakuences.py: error: unrecognized arguments: Sbicolor.fa

**Comment by EvanForsythe** [comment]
The "-f" flag should be used without actually listing the name of the file (squeakuences recognized the name of the file automatically).
